# Generated by Django 3.0.5 on 2020-04-05 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('url', models.CharField(max_length=300)),
                ('movies', models.FileField(upload_to='movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieApp.Streamer')),
            ],
        ),
    ]
